### ISSUE TITLE
Mount DeployR to `analyses`

### ISSUE THREAD

**Issue by cpritcha** [cpritcha/miracle-build#1]
How do I get DeployR to see my `analyses` folder? If I mount the "miracle/data" to DeployR like so

``` bash
# vagrant ssh dev1
sudo docker -d -v /opt/miracle/data:/home/deployr/deployr/7.4.1/deployr/external/data/public/data -p 7400:7400 deployr 
```

DeployR does not show my datasets in the Repository Manager. What do I need to change @warmdev?

**Comment by warmdev** [comment]
The datasets will not show up in the Repository Manager, but it can be referenced from the code using `deployrExternal` and the code will work fine. Quoted from: http://deployr.revolutionanalytics.com/documents/admin/bigdata/ (last paragraph):

> Note: Currently there is no user interface to display the names of the files in this directory. Additionally, due to the potentially large size of the data, we do not expose any API or other facility for moving data into the external directories.

**Comment by cpritcha** [comment]
Great. It might work then!

When I try to run the `Example1.R` script I get a `Package Not Found` error when `deployrUtils::deployrPackage("data.table")` is called. How do I fix that? Is [centralized management](http://deployr.revolutionanalytics.com/documents/admin/r-package-mgmt/) on by default?

**Comment by warmdev** [comment]
Since we are using the `admin` account, it shouldn't matter. I'll investigate the package issue.

**Comment by warmdev** [comment]
Are you running using the admin UI or the API?

**Comment by cpritcha** [comment]
I'm using the UI. I went to http://localhost:7400/repository-manager/#/repository/file/admin/root/Example1.R/latest/script/debug and pressed the `Run` button.

**Comment by warmdev** [comment]
This is due to the Docker image missing `g++` for building the dependencies. I'll change the Dockerfile.

**Comment by warmdev** [comment]
In the mean time, you can login onto the `deployr` container and manually install the package

```
sudo docker exec -i -t container_id /bin/bash
#inside container
yum install -y gcc-c++
```

**Comment by cpritcha** [comment]
ok. I'll try that out.
